### ISSUE TITLE
Make installing AMUSE easier (maybe with pip?)

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#163] opened 2017-09-21 08:40 UTC
If AMUSE could be installed with a simple 'pip install amuse', that would make it much more accessible.
https://packaging.python.org/tutorials/distributing-packages/ details the necessities for this. 

Issues this depends on (incomplete):
#144 #133

**Comment by rieder** [comment] 2017-09-21 10:34
I'm not at all sure if it will be possible to install AMUSE fully in this way, especially taking into account the community codes. However, it should be possible for the 'core' (minimal) AMUSE.

**Comment by rieder** [comment] 2018-02-06 02:56
Relates to #186

**Comment by ipelupessy** [comment] 2018-06-25 12:10
I have added this to team sprint project

**Comment by egpbos** [comment] 2018-06-27 08:56
Now that we can build and run almost all of Amuse on macOS using conda (#235), I think the last step of actually making Amuse a conda package (also for Linux) would be relatively easy.

The choice between conda and pip depends a bit on the progress on decoupling Amuse's core from the community packages. Amuse core depends almost exclusively on Python packages (see https://github.com/amusecode/amuse/blob/master/.travis.yml#L30; only exception is the Fortran compiler, which can probably easily be taken out), so for Amuse core, pip would be sufficient. Those Python packages may in turn depend on libraries that still need to be installed, but that is probably manageable. However, if people want to install the whole Amuse package, they will need some non-Python packages. These are available on conda, but not on pip.

**Comment by egpbos** [comment] 2018-06-27 08:58
So related to #107 :)

**Comment by rieder** [comment] 2019-02-19 16:43
Hmm, the real problem here is a line in support/create_codes.py that overwrites the data_directory with something relative to '/' (line 115). This fails. Line 115 overwrites 'data_dir' set in line 114, which is the correct way of setting it. Removing line 115 makes pip install AMUSE.

**Comment by rieder** [comment] 2019-02-19 17:50
I managed to upload & install a slightly modified (minus a few codes) version of AMUSE to PyPI, and install it via pip:
https://pypi.org/project/amuse/

**Comment by ipelupessy** [comment] 2019-02-20 09:22
hmm, apperently line 115 is much older than I thought....

**Comment by ipelupessy** [comment] 2019-02-20 09:33
I think the problem is that data_dir in the run of GenerateInstallIni is used to fill in configuration of amuserc, assuming the --root will be the "/" of the install target (ie build for a package manager), while in the run of  InstallLibraries its used in the script to copy stuff to...

**Comment by rieder** [comment] 2019-02-26 17:34
I uploaded a new version to PyPI, see branch 
https://github.com/rieder/amuse/tree/release-12.0a3 for the source.
I had to remove Mesa, EVTwin and SimpleX to fit in the required maximum size.

**Comment by rieder** [comment] 2019-02-26 17:35
(also the long description is now more appropriate)

**Comment by ipelupessy** [comment] 2019-06-30 20:33
fixed by release 12.0

**Closed by ipelupessy** 2019-06-30 20:33 UTC
Labels: feature request, installation
