### ISSUE TITLE
Missing defs.h when building athena in AMUSE 11.2

### ISSUE THREAD

**Issue by vanzod** [amusecode/amuse#400] opened 2019-04-18 21:33 UTC
**Describe the bug**
The build of `athena` fails due to missing `defs.h`. This file is generated by `configure` which as far as I can tell it is not called before `make`.

**To Reproduce**
Nothing more than the standard `configure`/`make`.

**Expected behavior**
I would expect the build script to invoke `configure` before running `make` so that the `defs.conf` file is generated.

**Logs**
```
 ****************************************************************************************************
Building code: athena, target: all, in directory: src/amuse/community/athena
****************************************************************************************************
make[1]: Entering directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/athena'
/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/build.py --type=c interface.py AthenaInterface -o worker_code.cc
/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/build.py --type=h interface.py -i amuse.support.codes.stopping_conditions.StoppingConditionInterface AthenaInterface -o worker_code.h
cp -r src/athena build
mpicc -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -fPIC -DAMUSE -g    -Ibuild/src -I/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/lib/stopcond -c -o build/interface_4.1.o interface_4.1.c 
interface_4.1.c:18:18: fatal error: defs.h: No such file or directory
 #include "defs.h"
                  ^
compilation terminated.
Makefile:173: recipe for target 'build/interface_4.1.o' failed
make[1]: *** [build/interface_4.1.o] Error 1
make[1]: Leaving directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/athena'
```

**Environment (please complete the following information):**
 - OS and version: Debian 9.8
 - Compiler: GCC 6.4.0

**Comment by rieder** [comment] 2019-04-19 08:15
Hi @vanzod,
Could you send us a bit more information, especially
- which version of AMUSE are you using (git or otherwise?) 
- the config.mk, config.log and build.log files
I think this issue is related to some configuration problem rather than missing files, likewise for #401 and #402.

**Comment by vanzod** [comment] 2019-04-19 13:41
Hi @rieder!
The version I am using is 11.2 from amusecode.org.
Here are the logs you requested.

_config.log_
https://gist.github.com/vanzod/cfb2c390a1539e88f947102264bd0557

_config.mk_
https://gist.github.com/vanzod/ace45d07734152bcd4489ecb9c67dcc3

_build.log_
https://gist.github.com/vanzod/43e7d52fe00b78b8f5b9bf2465701d8d

**Comment by ipelupessy** [comment] 2019-04-21 14:36
for all three problems it seems the make is skipping a dependency - did you start from a clean directory? (ie no files left from a previous possibly broken build..). Otherwise you can do:
make distclean in the amuse root and try again (starting ./configure etc)

**Comment by vanzod** [comment] 2019-04-21 18:34
@ipelupessy Yes, every build attempt is done in a freshly decompressed source directory.

**Comment by ipelupessy** [comment] 2019-04-25 07:34
hmm, still a bit mistifying: can you try to build the codes from within their directory, e.g. 
src/amuse/community/athena and then make?

maybe also post the output of (from within the directory):
```
make -n -p
```
are you using gmake?

**Comment by rieder** [comment] 2019-06-18 09:48
Any progress on this (and #401 #402)? I cannot reproduce it...

**Comment by vanzod** [comment] 2019-06-18 12:56
@rieder Sorry, it fell off the radar. I'll try to get back to it asap.

**Comment by rieder** [comment] 2019-08-27 11:00
I cannot reproduce this, closing for now. Please feel free to reopen.

**Closed by rieder** 2019-08-27 11:00 UTC
Labels: bug
