### ISSUE TITLE
MPFR detection issues

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#662] opened 2020-07-25 09:25 UTC
**Describe the bug**
sometimes (always?) the pkg-config for mpfr does not add the correct directories for the -I and -L flags, typically this doesn't matter, but some (mac) configurations  do not seem to find it then..

**To Reproduce**
see the discussion in issue #609 

**Expected behavior**
correct detection of mpfr location

**Environment (please complete the following information):**
mainly macos

**Additional context**
I have not yet found another project where this is done correctly...

**Comment by rieder** [comment] 2020-07-25 09:47
This is a duplicate of #209

**Closed by rieder** 2020-07-25 09:47 UTC
Labels: bug, duplicate
