### ISSUE TITLE
Allow ph4 to function with zero particles

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#561] opened 2019-12-24 14:00 UTC
Recent PR #558 fixed some issues with ph4 for 0 particles. However, calling evolve_model when no particles are added still results in a crash (unlike other codes, e.g. Hermite, BHTree).

The use case for running with 0 particles is e.g. a Bridged system where stars have not formed yet, but will be added to ph4 once formed.

It would be good if this can work without a workaround.

@stevemcmillan could you look at this?

**Comment by stevemcmillan** [comment] 2019-12-24 22:50
Yes, I will fix this.

**Comment by stevemcmillan** [comment] 2020-01-04 04:20
I'm issuing a pull request to merge my fix for this.  The new test_ph4.py works as intended.  If you have a specific script that shows the problem, please use it to check the modified code.

**Comment by rieder** [comment] 2020-01-06 11:03
Thanks Steve. Testing this today.

**Closed** 2020-01-06 11:10 UTC
Labels: feature request
