### ISSUE TITLE
fi - Missing musehelpers with AMUSE 11.2

### ISSUE THREAD

**Issue by vanzod** [amusecode/amuse#402] opened 2019-04-18 22:21 UTC
**Describe the bug**
The build of `fi` fails since the `MuseHelpers` module cannot be found.

**To Reproduce**
Nothing more than the standard `configure`/`make`.

**Logs**
```
****************************************************************************************************
Building code: fi, target: all, in directory: src/amuse/community/fi
****************************************************************************************************
make[1]: Entering directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/fi'
gfortran
gfortran
/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/build.py --type=f90 --needs-mpi=false interface.py FiInterface -o worker_code.f90
mkdir -p build
ln -s ../src/Makefile  build/Makefile
mpifort -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fdefault-real-8 -O3 -ffree-line-length-256 -frecord-marker=4  -I/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/lib/stopcond -Ibuild -c -o interface.o interface.f90
interface.f90:2:8:

     use MuseHelpers
        1
Fatal Error: Can't open module file ‘musehelpers.mod’ for reading at (1): No such file or directory
compilation terminated.
Makefile:139: recipe for target 'interface.o' failed
make[1]: *** [interface.o] Error 1
make[1]: Leaving directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/fi'
```

**Environment (please complete the following information):**
 - OS and version: Debian 9.8
 - Compiler: GCC 6.4.0

**Comment by rieder** [comment] 2019-08-27 10:59
I cannot reproduce this, closing for now. Please feel free to reopen.

**Closed by rieder** 2019-08-27 10:59 UTC
Labels: bug
