### ISSUE TITLE
capreole - Missing amuse_helper with AMUSE 11.2

### ISSUE THREAD

**Issue by vanzod** [amusecode/amuse#401] opened 2019-04-18 22:15 UTC
**Describe the bug**
The build of `capreole` fails since the `amuse_helpers` module cannot be found.

**To Reproduce**
Nothing more than the standard `configure`/`make`.

**Expected behavior**
The module `amuse_helpers` location should be corrected so that it can be found at build time.

**Logs**
```
****************************************************************************************************
Building code: capreole, target: all, in directory: src/amuse/community/capreole
****************************************************************************************************
make[1]: Entering directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/capreole'
mkdir build
cp src/Makefile build/Makefile
/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/build.py --type=f90 interface.py CapreoleInterface -o worker_code.f90
mpifort -O2 -ftree-vectorize -march=native -fno-math-errno  -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC    -Ibuild -I/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/lib/stopcond -c -o build/interface.o interface.F90 
interface.F90:2:6:

   use amuse_helpers
      1
Fatal Error: Can't open module file ‘amuse_helpers.mod’ for reading at (1): No such file or directory
compilation terminated.
Makefile:55: recipe for target 'build/interface.o' failed
make[1]: *** [build/interface.o] Error 1
make[1]: Leaving directory '/tmp/AMUSE/11.2/foss-2017b-Python-2.7.14/amuse-11.2/src/amuse/community/capreole'
```

**Environment (please complete the following information):**
 - OS and version: Debian 9.8
 - Compiler: GCC 6.4.0

**Comment by rieder** [comment] 2019-08-27 10:59
I cannot reproduce this, closing for now. Please feel free to reopen.

**Closed by rieder** 2019-08-27 10:59 UTC
Labels: bug
