### ISSUE TITLE
Change default parameters in MESA(version='2208') within amuse 

### ISSUE THREAD

**Issue by adamparkosidis** [amusecode/amuse#904] opened 2022-11-21 09:25 UTC
Hello,I am using MESA(version='2208') within amuse and these are the default parameters of this version:
```
AGB_wind_scheme: 1
RGB_wind_scheme: 1
blocker_wind_efficiency: 0.1
de_jager_wind_efficiency: 0.8
dutch_wind_efficiency: 0.8
herwig_convective_overshoot_parameter: 0.0
max_age_stop_condition: 1e+36 yr
max_iter_stop_condition: -1111
metallicity: 0.02
min_timestep_stop_condition: 1e-06 s
mixing_length_ratio: 2.0
reimers_wind_efficiency: 0.5
semi_convection_efficiency: 0.0
stabilize_new_stellar_model_flag: True
```
I am trying to alter `herwig_convective_overshoot_parameter` and `semi_convection_efficiency` parameters. If I understand correctly I must do this within amuse and NOT try to alter the inlist files of mesa (I think that AMUSE_inlist is the file that mesa within amuse reads),  thus I use the lines:
```
code.set_convective_overshoot_parameter(0.3)
 code.set_semi_convection_efficiency(1.0)
```
I face two problems:
1) It seems that the order of the commands affects mesa model. For example, if I try to add particles after the aforementioned lines (eg `ste_ev_giant = code.particles.add_particle(giant)` ) the mesa parameters return to the default values. Hence, in which order should someone alter the model parameters?
2) I placed the lines that alter the default parameters exactly before the evolution of my model (eg before line `code.evolve_model(keep_synchronous = False)`) and I printed the parameters after the evolution. At first sight seems like it worked:
```
AGB_wind_scheme: 1
RGB_wind_scheme: 1
blocker_wind_efficiency: 0.1
de_jager_wind_efficiency: 0.8
dutch_wind_efficiency: 0.8
herwig_convective_overshoot_parameter: 0.3          <-----
max_age_stop_condition: 1e+36 yr
max_iter_stop_condition: -1111
metallicity: 0.02
min_timestep_stop_condition: 1e-06 s
mixing_length_ratio: 2.0
reimers_wind_efficiency: 0.5
semi_convection_efficiency: 1.0                     <-----
stabilize_new_stellar_model_flag: True
```
but when I try to double check by producing some plots it seems like it did not.  Here are two plots for semiconvection coefficient = 1.0 and varying overshooting coefficient. The first is produced by  the MESA(version='2208') within amuse, while  the second by the latest MESA version in date. Clearly the first does not take into account the overshooting as all the lines overlap. Is there any other 'switch' that needs to be turned on in MESA(version='2208') in order to take into account overshooting and semiconvection?
Thank you advance

![amuse_mesa](https://user-images.githubusercontent.com/84510854/203013662-52a5f845-db72-46e7-849f-974165d8dc20.png)

![mesa](https://user-images.githubusercontent.com/84510854/203013688-70066d68-2295-44a9-9bb4-e18359659cbd.png)

**Comment by rieder** [comment] 2022-11-21 16:29
Adding @rjfarmer to this issue - it's best to keep discussion here rather than on Slack since Slack deletes the history after 30 days.

**Comment by rjfarmer** [comment] 2022-11-22 16:09
The problem is this line:
https://github.com/amusecode/amuse/blob/616fec2165fe32e144259fda70a85ed348539556/src/amuse/community/mesa_r2208/interface.py#L1425

When it gets called its resetting all the AMUSE_ settings back to thier defaults then re-calling the fortran set_ functions. Commenting that out makes the ``print(se_code.parameters)`` show the correct values and mesa also shows the correct values being stored inside its data structures (and does not show a second call to the set_ functions). 

The ``self.parameters.send_not_set_parameters_to_code()`` code is found at:
https://github.com/amusecode/amuse/blob/616fec2165fe32e144259fda70a85ed348539556/src/amuse/datamodel/parameters.py#L137

Is this needed? Is there meant to be some way to set the parameters and make sure they get marked as not needing to be set to defaults?

**Comment by adamparkosidis** [comment] 2022-11-24 08:38
So, in order to overcome this problem, do I have to comment out the line `self.parameters.send_not_set_parameters_to_code() ` in `amuse/src/amuse/community/mesa_r2208/interface.py`?

**Comment by rieder** [comment] 2022-11-24 09:33
If a parameter is set with a setter (as I assume they would be in Mesa as in other codes), it should not be reset - it should have `is_set = True`. So this is puzzling.

**Comment by rieder** [comment] 2022-11-24 09:35
It sounds like `is_set` is not set to `True`, so fixing that would be the solution.

**Comment by adamparkosidis** [comment] 2022-11-24 10:14
So, I should not comment out anything in the `interface.py` file, but just add an argument to my lines :
```
code.set_convective_overshoot_parameter(0.3, is_set=True)
code.set_semi_convection_efficiency(1.0,is_set=True)
```
Is that right?

**Comment by rieder** [comment] 2022-11-24 10:23
No, I don't think it is. Please let me look into it. I'm sorry it takes a little while.

**Comment by rieder** [comment] 2022-11-24 11:19
Ah, I think I see the problem. You should not call `code.set_convective_overshoot_parameter` or `code.set_semi_convection_efficiency`, but `code.parameters.convective_overshoot_parameter = (value)` (etc).

**Comment by rieder** [comment] 2022-11-24 11:21
Seems to work then:
```
In [1]: from amuse.lab import *

In [2]: star = Particle(mass=1.0 | units.MSun)

In [3]: evo = Mesa(version="2208")

In [4]: print(evo.parameters)
AGB_wind_scheme: 1
RGB_wind_scheme: 1
blocker_wind_efficiency: 0.1
de_jager_wind_efficiency: 0.8
dutch_wind_efficiency: 0.8
herwig_convective_overshoot_parameter: 0.0
max_age_stop_condition: 1e+36 yr
max_iter_stop_condition: -1111
metallicity: 0.02
min_timestep_stop_condition: 1e-06 s
mixing_length_ratio: 2.0
reimers_wind_efficiency: 0.5
semi_convection_efficiency: 0.0
stabilize_new_stellar_model_flag: True


In [5]: evo.parameters.semi_convection_efficiency = 1.0

In [6]: evo.parameters.herwig_convective_overshoot_parameter = 0.3

In [7]: evo.particles.add_particle(star)
Out[7]: <amuse.datamodel.particles.Particle at 0x1062da180>

In [8]: print(evo.parameters)
AGB_wind_scheme: 1
RGB_wind_scheme: 1
blocker_wind_efficiency: 0.1
de_jager_wind_efficiency: 0.8
dutch_wind_efficiency: 0.8
herwig_convective_overshoot_parameter: 0.3
max_age_stop_condition: 1e+36 yr
max_iter_stop_condition: -1111
metallicity: 0.02
min_timestep_stop_condition: 1e-06 s
mixing_length_ratio: 2.0
reimers_wind_efficiency: 0.5
semi_convection_efficiency: 1.0
stabilize_new_stellar_model_flag: True
```

**Comment by adamparkosidis** [comment] 2022-11-25 08:37
Indeed seems to work now. Thank you very much for your help

**Closed** 2022-11-25 08:51 UTC
Labels: question
