### ISSUE TITLE
plotting molecular cloud collapse with sink

### ISSUE THREAD

**Issue by dnrgodilano7** [amusecode/amuse#914] opened 2022-12-04 23:03 UTC
Good day. 
I'm testing the molecular cloud collapse with sink example with the pre-set values but with time-step interval of 1Myr.
The simulation is long but it is going well, i.e. with merges and formation of new stars.
I was able to use the plotting tool to plot pre-sink/formation.
But when I try to plot the ones with formed stars I get this error:

    Traceback (most recent call last):
      File "/Users/dnrgodilano7/Documents/AMUSE/trial/molec-cld-clps-snk/plot_molecular_cloud_collapse_with_sinks.py", line 147, in <module>
    plot_molecular_cloud(o.filename)
      File "/Users/dnrgodilano7/Documents/AMUSE/trial/molec-cld-clps-snk/plot_molecular_cloud_collapse_with_sinks.py", line 56, in plot_molecular_cloud
     hydro = Hydro(Fi, gas, sinks)
      File "/Users/dnrgodilano7/Documents/AMUSE/trial/molec-cld-clps-snk/hydrodynamics_class.py", line 106, in __init__
    self.code.gas_particles.add_particles(self.gas_particles)
      File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/datamodel/particles.py", line 626, in add_particles
    self.add_particles_to_store(keys, attributes, converted)
      File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/datamodel/particles.py", line 1339, in add_particles_to_store
         self._private.attribute_storage.add_particles_to_store(keys, attributes, values)
      File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/datamodel/incode_storage.py", line 827, in add_particles_to_store
        indices = self.new_particle_method.add_entities(attributes, values)
       File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/datamodel/incode_storage.py", line 481, in add_entities
        list_arguments,keyword_arguments = self.convert_attributes_and_values_to_list_and_keyword_arguments(attributes, values)
      File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/datamodel/incode_storage.py", line 379, in convert_attributes_and_values_to_list_and_keyword_arguments
        raise exceptions.MissingAttributesAmuseException(
    amuse.support.exceptions.MissingAttributesAmuseException: To add particles to this code you need to specify the 'u' attribute

I can't find the part where I could input/change the attribute. 
I checked the output table of the gas/star properties and it seems ok:

    Ly           Lz    birth_age         mass         name       radius           vx           vy           vz            x            y            z
                        -  0.001 * m**2 * kg * s**-1  0.001 * m**2 * kg * s**-1  0.001 * m**2 * kg * s**-1            s           kg         none            m    m * s**-1    m * s**-1    m * s**-1            m            m            m
    ====================  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========  ===========
    16341000225946502622    0.000e+00    0.000e+00    0.000e+00    1.263e+14    7.476e+30         Star    8.390e+14     1.007e+03    1.917e+02   -7.852e+02    7.337e+15    1.305e+16   -1.698e+15
    14105080017523659441    0.000e+00    0.000e+00    0.000e+00    1.263e+14    2.077e+29         Star    5.146e+14    2.545e+03   -1.443e+02   -1.357e+03    7.304e+15    1.284e+16    1.530e+14
    18380933387359736910    0.000e+00    0.000e+00    0.000e+00    1.263e+14    2.077e+29         Star    5.559e+14    5.391e+02    1.354e+02    5.604e+02    6.498e+15    1.422e+16   -9.082e+15
     5632179285908800617    0.000e+00    0.000e+00    0.000e+00    1.263e+14    2.077e+29         Star    6.413e+14    3.156e+02    5.056e+02   -9.170e+02    1.680e+16    1.394e+16   -6.427e+15
     4046689910357451679    0.000e+00    0.000e+00    0.000e+00    1.263e+14    2.077e+29         Star    5.649e+14    1.630e+03   -3.240e+02   -4.386e+02    8.290e+15    9.756e+15   -1.089e+15
     2014063539602757451    0.000e+00    0.000e+00    0.000e+00    1.263e+14    2.077e+29         Star    8.090e+14    4.977e+02    7.948e+02   -1.254e+03    8.351e+15    1.347e+16   -1.735e+15
    .
    .
    .

Is there a way to solve this plotting issue?
Thank you.

**Comment by MJCWilhelm** [comment] 2022-12-05 08:41
Hi there! The particles you're trying to add are missing the particle property u, which is the internal energy of the gas (basically the temperature; it's actually each gas atom/molecule's specific kinetic energy, or its thermal speed squared). This is required for gas particles, but not for star/dark matter particles (those only require the standard N-body properties). 

If I'm reading the plot_molecular_cloud_collapse_with_sinks script correctly, it only actually shows stars where there is sufficiently dense gas, not where there were stars in the original data. 

My suggestion to fix it would be to add the stars to Hydro as sinks, and then replace the sph.gas_particles in `get_stars_from_molecular_clous` [sic] with sph.star_particles.

This is very confusing, and really should be fixed...

**Comment by rieder** [comment] 2022-12-05 09:59
Somehow, the script seems to believe you're adding gas particles when you're not.
Adding `u` isn't the solution - you'd just be doing something incorrect then.
I'll have a look at the script. In the meantime, could you let us know if you made any modifications, or if you call the script with any nonstandard parameters?

**Comment by dnrgodilano7** [comment] 2022-12-05 11:01
> Hi there! The particles you're trying to add are missing the particle property u, which is the internal energy of the gas (basically the temperature; it's actually each gas atom/molecule's specific kinetic energy, or its thermal speed squared). This is required for gas particles, but not for star/dark matter particles (those only require the standard N-body properties).

> If I'm reading the plot_molecular_cloud_collapse_with_sinks script correctly, it only actually shows stars where there is sufficiently dense gas, not where there were stars in the original data.

Thank you for explaining the particle property!

> My suggestion to fix it would be to add the stars to Hydro as sinks, and then replace the sph.gas_particles in `get_stars_from_molecular_clous` [sic] with sph.star_particles.

I'm not sure if it is by uncommenting (and commenting) this part in the Hydro code  is what you meant

            # self.star_particles.add_sinks(newstars)
            self.star_particles.add_particles(newstars)

but I did see there is an identifier for gas or star and function for the sink

    if len(self.gas_particles) > 0:
            self.code.gas_particles.add_particles(self.gas_particles)
    if len(self.star_particles) > 0:
            self.code.dm_particles.add_particles(self.star_particles)

    if len(self.star_particles) > 0:
            print("Sink masses:", len(self.code.dm_particles.mass))
            print("Sink masses:", len(self.star_particles.mass))

    if len(self.star_particles) > 0:
            sinks = new_sink_particles(self.star_particles)
            sinks.accrete(self.gas_particles)
            for si in range(len(self.star_particles)):
                self.star_particles[si].Lx += sinks[si].angular_momentum[0]
                self.star_particles[si].Ly += sinks[si].angular_momentum[1]
                self.star_particles[si].Lz += sinks[si].angular_momentum[2]

And in my run I saw the sinks taking place:

    Cool gas for another dt= 0.500345151647 Myr
    Let gravity take care of merging sinks
    identify groups..
    merging sink sets... 
    Merge stars: N=  36
    old radius: [ 2907.27775407  1526.97884861  1977.16989916  4115.42815093  4145.24667059
      1036.07319853  1423.64850584  2056.97020906  1029.86774969  2249.30472272
      2122.46187841  2462.23730398  1096.98229849  1080.10026767  3420.88657425
      2135.02187616  1401.41423528  1208.76506515  1217.62468354  1063.29178809
      2330.29078458  2267.28718153  1200.8261301   1220.08126696  3033.23517332
      1452.61619515  2178.72542146  5098.30385649  1691.4081548   3418.19708935
      2938.11495262  5608.03808802  2792.39969631  1878.42953678  2358.56162296
      1720.26574466]
    new radius: [ 5608.03808802]
    Two stars (M= [2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29, 2.07676725488e+29] kg ) collided at d= 1.50714307589e+16 m
    stars merged
    Merge stars: N=  1
    old radius: [ 3439.92208256]
    new radius: [ 3439.92208256]
    Two stars (M= [2.07676725488e+29] kg ) collided at d= 1.47690548022e+16 m
    stars merged
    Merge stars: N=  1
    old radius: [ 3715.9538189]
    new radius: [ 3715.9538189]
    Two stars (M= [2.07676725488e+29] kg ) collided at d= 1.80799074814e+16 m
    stars merged
    .
    .
    .

I replaced the plotting with sph.star_particles but I still get the error for u.


> Somehow, the script seems to believe you're adding gas particles when you're not.
> I'll have a look at the script. In the meantime, could you let us know if you made any modifications, or if you call the script with any nonstandard parameters?

I only changed the tilmestep to 1Myr.
Also, there was an error saying duplicate/file exists when it starts to detect star formations. 
It seems to be a repetition in the naming. 
I changed the overwrite_file to return True so it will replace the duplicate.
Thanks!

**Comment by rieder** [comment] 2022-12-05 11:07
Hi,
>Also, there was an error saying duplicate/file exists when it starts to detect star formations. 
It seems to be a repetition in the naming. 
I changed the overwrite_file to return True so it will replace the duplicate.
Thanks!

That is indeed the cause of the problem, but not the right solution. The file needs to be appended to rather than overwritten. I have fixed this now in `hydrodynamics_class.py`, replacing this (and keeping everything else as it originally was) will solve the issue.

**Comment by dnrgodilano7** [comment] 2022-12-05 11:31
> Hi,
> 
> > Also, there was an error saying duplicate/file exists when it starts to detect star formations.
> > It seems to be a repetition in the naming.
> > I changed the overwrite_file to return True so it will replace the duplicate.
> > Thanks!
> 
> That is indeed the cause of the problem, but not the right solution. The file needs to be appended to rather than overwritten. I have fixed this now in `hydrodynamics_class.py`, replacing this (and keeping everything else as it originally was) will solve the issue.

That fixed the problem. Thank you so much!

**Closed** 2022-12-05 11:54 UTC
Labels: question
