### ISSUE TITLE
No workers built for installed amuse packages

### ISSUE THREAD

**Issue by sergio0711** [amusecode/amuse#953] opened 2023-04-25 02:02 UTC
**Describe the bug**
I installed my AMUSE without any problem. However, when I tried to run an event-driven example calling the SeBa community code, it showed the next error:

exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
amuse.support.exceptions.CodeException: The worker application does not exist, it should be at:
/Users/sergiosan/Amuse-env/lib/python3.9/site-packages/amuse/_workers/seba_worker
/Users/sergiosan/Amuse-env/lib/python3.9/site-packages/amuse/_workers/seba_worker
/Users/sergiosan/Amuse-env/lib/python3.9/site-packages/amuse/community/seba/seba_worker
/Users/sergiosan/Amuse-env/lib/python3.9/site-packages/amuse/rfi/seba_worker

I just realised that all the cummunity codes have their respective worker executable files, but the one from Seba is not there.  I

**Environment (please complete the following information):**
 - I have a MacBook Pro with M1 processor.

Am I missing something or I forgot to include the worker?

**Comment by sergio0711** [comment] 2023-04-25 14:26
Completely odd.. It never happened to me. It's just that specific file.

When I do `pip list | grep amuse` I got all the community codes installed:

amuse                    2023.3.0
amuse-athena             2023.3.0
amuse-bhtree             2023.3.0
amuse-bse                2023.3.0
amuse-capreole           2023.3.0
amuse-evtwin             2023.3.0
amuse-fastkick           2023.3.0
amuse-fi                 2023.3.0
amuse-fractalcluster     2023.3.0
amuse-framework          2023.3.0
amuse-gadget2            2023.3.0
amuse-galactics          2023.3.0
amuse-galaxia            2023.3.0
amuse-halogen            2023.3.0
amuse-hermite            2023.3.0
amuse-hop                2023.3.0
amuse-huayno             2023.3.0
amuse-kepler             2023.3.0
amuse-kepler-orbiters    2023.3.0
amuse-mameclot           2023.3.0
amuse-mercury            2023.3.0
amuse-mmams              2023.3.0
amuse-ph4                2023.3.0
amuse-phigrape           2023.3.0
amuse-seba               2023.4.0
amuse-secularmultiple    2023.3.0
amuse-simplex            2023.3.0
amuse-smalln             2023.3.0
amuse-sphray             2023.3.0
amuse-sse                2023.3.0
amuse-twobody            2023.3.0


Including SeBa. Does it have something to do with the OS? On the other hand... Can I get the worker in any repository?

**Comment by rieder** [comment] 2023-04-26 02:06
The worker should be built automatically when you install via pip, if it's not there the installation should fail.
The OS is not a problem either.
I just tested amuse-seba 2023.4.0 which you have installed, and I have the worker.

Could you try uninstalling amuse-seba (`pip uninstall amuse-seba`), then removing your pip cache files (`rm -r ~/Library/Caches/pip/wheels/*`) and installing amuse-seba again (`pip install --upgrade amuse-seba`)?

**Comment by sergio0711** [comment] 2023-04-26 05:19
I have applied the commands you proposed. After uninstalling SeBa I checked that the folder was properly removed, including the pip cache files. Finally, I re-install amuse-seba one more time but I'm getting the same folder without the worker. Definitely, very strange...

The only files that appear are:
- __init__.py
- __pycache__ (folder)
- download.py
- interface.py
- version.py

**Comment by rieder** [comment] 2023-04-27 04:53
Ok, so the problem is not Seba then, but more global.
I'm surprised that these packages install after failing to build the worker, that seems like the real bug here.

Your issue would then probably originate from a problem with the prerequisites, perhaps the compilers are not correct.
Did you upgrade anything after originally installing `amuse-framework`?
Could you attach the AMUSE config file (should be in `/Users/sergiosan/Amuse-env/share/amuse/config.mk`)?

Your OS and Python version are not a problem, I'm running the same.

**Comment by sergio0711** [comment] 2023-04-27 20:42
For you first question. I haven't done any upgrade of AMUSE after installing it the first time. Just installed some libraries in python for my PhD project, particularly the one called Isochrones.

Now, here below I attached the file you asked me to look for (sorry for the huge block of text):

`
# amuse configuration generated by ./configure from config.mk.in

PYTHON=/Users/sergiosan/Amuse-env/bin/python
CODE_GENERATOR=amusifier

#
# PYTHON embedding
#
PYTHON_DEV=no
CYTHON=/Users/sergiosan/opt/anaconda3/bin/cython
PYTHONCONFIG='no'
PYTHONDEV_CFLAGS=
PYTHONDEV_LDFLAGS=


#
# Compilers, for compiling without MPI
# these compilers must be the same or compatible with
# the mpi compilers
#
CXX=g++
CC=gcc
FC=/opt/local/bin/gfortran-mp-12
GFORTRAN_VERSION=12.2.0
IFORT_VERSION=
FC_ISO_C_AVAILABLE=yes

#
# Default flags, append to these in the makefiles
#
CXXFLAGS=-g -O2 -fno-common
CFLAGS=-g -O2 -fno-common
FCFLAGS=-g -O2 -fno-common
LDFLAGS=

#
# MPI Compilers
#
MPI_ENABLED=yes
MPICXX=mpicxx
MPICC=mpicc
MPIFC=mpif90
MPIEXEC=/opt/local/bin/mpiexec

MPI_CFLAGS=-I/opt/local/include/openmpi-gcc12
MPI_CXXFLAGS=-I/opt/local/include/openmpi-gcc12
MPI_FCFLAGS=-Wl,-flat_namespace -Wl,-commons,use_dylibs -I/opt/local/lib/openmpi-gcc12
MPI_CLIBS=-L/opt/local/lib -lmpi
MPI_CXXLIBS=-L/opt/local/lib -lmpi_cxx -lmpi
MPI_FCLIBS=-Wl,-commons,use_dylibs -I/opt/local/lib/openmpi-gcc12 -L/opt/local/lib/openmpi-gcc12 -L/opt/local/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

#
# Java
#
JAVA_ENABLED=yes
JAVA=/usr/bin/java
JAVAC=/usr/bin/javac
JAR=/usr/bin/jar
JAVA_VERSION=1.8

#
# OpenMP
#

OPENMP_ENABLED=no
OPENMP_FCFLAGS=-fopenmp
OPENMP_CFLAGS=
    
#
# Libraries: FFTW, GSL, HDF5, CUDA, SAPPORO
#

FOUND_FFTW=yes
FFTW_FLAGS=-I/Users/sergiosan/opt/anaconda3/include
FFTW_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lfftw3 -lfftw3_threads
    
FOUND_GSL=yes
GSL_FLAGS=-I/opt/local/include
GSL_LIBS=-L/opt/local/lib -lgsl -lgslcblas

FOUND_GMP=yes
GMP_FLAGS=
GMP_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lgmp

FOUND_MPFR=yes
MPFR_FLAGS=
MPFR_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lmpfr -lgmp

HDF5_FLAGS=-I/Users/sergiosan/opt/anaconda3/include
HDF5_LIBS= -L/Users/sergiosan/opt/anaconda3/lib -lhdf5  -lcrypto -lcurl -lpthread -lz -ldl -lm
HDF5_FFLAGS=
HDF5_FLIBS= -L/Users/sergiosan/opt/anaconda3/lib 

NETCDF_PREFIX=.
NETCDF_FLAGS=
NETCDF_LIBS=
NETCDFF_PREFIX=.
NETCDFF_FLAGS=
NETCDFF_LIBS=

CUDA_ENABLED=no
NVCC=
NVCC_FLAGS=
CUDA_TK=/NOCUDACONFIGURED
CUDA_LIBS=-L/NOCUDACONFIGURED cuda cudart

FOUND_CL=no
CL_LIBS=
CL_FLAGS=

SAPPORO_VERSION=light
SAPPORO_LIBS=-L${AMUSE_DIR}/lib/sapporo_light -lsapporo 

FS_FLAGS=-I$(AMUSE_DIR)/lib/forsockets
FS_LIBS=-L$(AMUSE_DIR)/lib/forsockets -lforsockets

SC_FLAGS=-I$(AMUSE_DIR)/lib/stopcond
SC_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_MPI_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi
SC_MPI_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi

LAPACK_LIBS=-llapack
BLAS_LIBS=-lblas

export PYTHON CXX CC FC CXXFLAGS CFLAGS FCFLAGS MPICXX MPICC MPIFC LDFLAGS
export JAVA JAVAC JAVAH JAR JAVA_FLAGS
export FS_FLAGS FS_LIBS SC_FLAGS SC_CLIBS SC_FCLIBS SC_MPI_CLIBS SC_MPI_FCLIBS
export FFTW_FLAGS FFTW_LIBS
export GSL_FLAGS GSL_LIBS
export HDF5_FLAGS HDF5_LIBS
export OPENMP_FCFLAGS OPENMP_CFLAGS
export NVCC CUDA_TK CUDA_LIBS CUDA_ENABLED
export SAPPORO_VERSION SAPPORO_LIBS
export MPICFLAGS MPICCFLAGS MPIFCFLAGS
export IFORT_VERSION
export NVCC_FLAGS
export PYTHONDEV_LIBS PYTHONDEV_CFLAGS PYTHONDEV_LIBS
export FC_ISO_C_ENABLED
export LAPACK_LIBS BLAS_LIBS


ifdef AMUSE_DIR
export AMUSE_DIR
endif
`

**Comment by sergio0711** [comment] 2023-04-27 20:46
For you first question. I haven't done any upgrade of AMUSE after installing it the first time. Just installed some libraries in python for my PhD project, particularly the one called Isochrones.

Now, here below I attached the file you asked me to look for (sorry for the huge block of text):

````
# amuse configuration generated by ./configure from config.mk.in

PYTHON=/Users/sergiosan/Amuse-env/bin/python
CODE_GENERATOR=amusifier

#
# PYTHON embedding
#
PYTHON_DEV=no
CYTHON=/Users/sergiosan/opt/anaconda3/bin/cython
PYTHONCONFIG='no'
PYTHONDEV_CFLAGS=
PYTHONDEV_LDFLAGS=


#
# Compilers, for compiling without MPI
# these compilers must be the same or compatible with
# the mpi compilers
#
CXX=g++
CC=gcc
FC=/opt/local/bin/gfortran-mp-12
GFORTRAN_VERSION=12.2.0
IFORT_VERSION=
FC_ISO_C_AVAILABLE=yes

#
# Default flags, append to these in the makefiles
#
CXXFLAGS=-g -O2 -fno-common
CFLAGS=-g -O2 -fno-common
FCFLAGS=-g -O2 -fno-common
LDFLAGS=

#
# MPI Compilers
#
MPI_ENABLED=yes
MPICXX=mpicxx
MPICC=mpicc
MPIFC=mpif90
MPIEXEC=/opt/local/bin/mpiexec

MPI_CFLAGS=-I/opt/local/include/openmpi-gcc12
MPI_CXXFLAGS=-I/opt/local/include/openmpi-gcc12
MPI_FCFLAGS=-Wl,-flat_namespace -Wl,-commons,use_dylibs -I/opt/local/lib/openmpi-gcc12
MPI_CLIBS=-L/opt/local/lib -lmpi
MPI_CXXLIBS=-L/opt/local/lib -lmpi_cxx -lmpi
MPI_FCLIBS=-Wl,-commons,use_dylibs -I/opt/local/lib/openmpi-gcc12 -L/opt/local/lib/openmpi-gcc12 -L/opt/local/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

#
# Java
#
JAVA_ENABLED=yes
JAVA=/usr/bin/java
JAVAC=/usr/bin/javac
JAR=/usr/bin/jar
JAVA_VERSION=1.8

#
# OpenMP
#

OPENMP_ENABLED=no
OPENMP_FCFLAGS=-fopenmp
OPENMP_CFLAGS=
    
#
# Libraries: FFTW, GSL, HDF5, CUDA, SAPPORO
#

FOUND_FFTW=yes
FFTW_FLAGS=-I/Users/sergiosan/opt/anaconda3/include
FFTW_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lfftw3 -lfftw3_threads
    
FOUND_GSL=yes
GSL_FLAGS=-I/opt/local/include
GSL_LIBS=-L/opt/local/lib -lgsl -lgslcblas

FOUND_GMP=yes
GMP_FLAGS=
GMP_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lgmp

FOUND_MPFR=yes
MPFR_FLAGS=
MPFR_LIBS=-L/Users/sergiosan/opt/anaconda3/lib -lmpfr -lgmp

HDF5_FLAGS=-I/Users/sergiosan/opt/anaconda3/include
HDF5_LIBS= -L/Users/sergiosan/opt/anaconda3/lib -lhdf5  -lcrypto -lcurl -lpthread -lz -ldl -lm
HDF5_FFLAGS=
HDF5_FLIBS= -L/Users/sergiosan/opt/anaconda3/lib 

NETCDF_PREFIX=.
NETCDF_FLAGS=
NETCDF_LIBS=
NETCDFF_PREFIX=.
NETCDFF_FLAGS=
NETCDFF_LIBS=

CUDA_ENABLED=no
NVCC=
NVCC_FLAGS=
CUDA_TK=/NOCUDACONFIGURED
CUDA_LIBS=-L/NOCUDACONFIGURED cuda cudart

FOUND_CL=no
CL_LIBS=
CL_FLAGS=

SAPPORO_VERSION=light
SAPPORO_LIBS=-L${AMUSE_DIR}/lib/sapporo_light -lsapporo 

FS_FLAGS=-I$(AMUSE_DIR)/lib/forsockets
FS_LIBS=-L$(AMUSE_DIR)/lib/forsockets -lforsockets

SC_FLAGS=-I$(AMUSE_DIR)/lib/stopcond
SC_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_MPI_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi
SC_MPI_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi

LAPACK_LIBS=-llapack
BLAS_LIBS=-lblas

export PYTHON CXX CC FC CXXFLAGS CFLAGS FCFLAGS MPICXX MPICC MPIFC LDFLAGS
export JAVA JAVAC JAVAH JAR JAVA_FLAGS
export FS_FLAGS FS_LIBS SC_FLAGS SC_CLIBS SC_FCLIBS SC_MPI_CLIBS SC_MPI_FCLIBS
export FFTW_FLAGS FFTW_LIBS
export GSL_FLAGS GSL_LIBS
export HDF5_FLAGS HDF5_LIBS
export OPENMP_FCFLAGS OPENMP_CFLAGS
export NVCC CUDA_TK CUDA_LIBS CUDA_ENABLED
export SAPPORO_VERSION SAPPORO_LIBS
export MPICFLAGS MPICCFLAGS MPIFCFLAGS
export IFORT_VERSION
export NVCC_FLAGS
export PYTHONDEV_LIBS PYTHONDEV_CFLAGS PYTHONDEV_LIBS
export FC_ISO_C_ENABLED
export LAPACK_LIBS BLAS_LIBS


ifdef AMUSE_DIR
export AMUSE_DIR
endif
````
/
hola
/

**Comment by sergio0711** [comment] 2023-04-27 20:50
For you first question. I haven't done any upgrade of AMUSE after installing it the first time. Just installed some libraries in python for my PhD project, particularly the one called Isochrones.

Now, here below I attached the file `config.mk` you asked me to look for (I added `.txt` at the end for uploading without format error)

[config.mk.txt](https://github.com/amusecode/amuse/files/11347755/config.mk.txt)

**Comment by LourensVeen** [comment] 2024-06-17 06:51
I think we can close this, having resolved the issue during the workshop in New York. For future reference: the problem was caused by a mix of Intel-Homebrew, ARM-Homebrew, and MacPorts being installed, plus a funky PATH setup. After we disentangled all the different installers and tools, AMUSE built successfully.

**Closed by LourensVeen** 2024-06-17 06:51 UTC
Labels: bug
